name: Semgrep
on:
  pull_request: {}
  schedule:
    # Random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '29 6 * * *'

jobs:
  semgrep:
    uses: cloudticity/ct-gh-shared-workflows/.github/workflows/semgrep.yml@main
    # We must explicitly pass in the token secret as the shared workflow cannot inherit secrets from the org
    secrets:
      semgrepAppToken: ${{ secrets.SEMGREP_APP_TOKEN }}

